replicaCount: 1

image:
  repository: bitnami/elasticsearch
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 9200

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

nodeSelector: {}
tolerations: []
affinity: {}
