apiVersion: v2
name: rabbitmq
description: RabbitMQ message broker
type: application
version: 1.0.0
appVersion: "1.0"
keywords:
  - rabbitmq
home: https://github.com/MaheshBhairi2315/dkubex-helm-charts
sources:
  - https://github.com/MaheshBhairi2315/dkubex-helm-charts
maintainers:
  - name: DKubeX Team
    email: support@dkubex.io
